export const strings = {
  appName: "יאללה כרטיסים",

  nav: {
    review: "חזרה",
    inbox: "תיבה",
    lessons: "שיעורים",
    recordings: "הקלטות",
    stats: "סטטיסטיקה",
    browse: "עיון",
    notes: "פתקים",
    logout: "יציאה",
  },

  login: {
    title: "כניסה",
    passwordLabel: "סיסמה",
    submit: "כניסה",
    error: "סיסמה שגויה",
  },

  review: {
    title: "חזרה יומית",
    remaining: "נותרו",
    newToday: "חדשים היום",
    showAnswer: "הצג תשובה",
    again: "שוב",
    hard: "קשה",
    good: "טוב",
    easy: "קל",
    doneTitle: "סיימת להיום!",
    doneSubtitle: "אין כרטיסים נוספים לחזרה כרגע",
    playAudio: "נגן הקלטה",
    directionHeToAr: "עברית → ערבית",
    directionArToHe: "ערבית → עברית",
  },

  inbox: {
    title: "תיבת קליטה",
    pasteTab: "הדבקת טקסט",
    photoTab: "העלאת תמונה",
    pasteLabel: "הדבק כאן הערות שיעור",
    pasteSubmit: "נתח עם Gemini",
    photoLabel: "בחר תמונה או תמונות של המחברת",
    photoSubmit: "נתח תמונות עם Gemini",
    parsing: "מנתח...",
    tableTitle: "תוצאות לעריכה",
    colTranslit: "תעתיק בניקוד",
    colMeaning: "משמעות בעברית",
    colType: "סוג",
    colConfidence: "רמת ביטחון",
    colNotes: "הערות",
    typeWord: "מילה",
    typePhrase: "ביטוי",
    typeSentence: "משפט",
    confidenceLow: "נמוכה",
    confidenceHigh: "גבוהה",
    deleteRow: "מחק שורה",
    addRow: "הוסף שורה",
    duplicateWarning: "כרטיס דומה כבר קיים",
    commit: "הוסף לחפיסה",
    committing: "שומר...",
    committed: "נוספו הכרטיסים בהצלחה",
    emptyState: "אין עדיין פריטים לעריכה",
    lessonLabel: "שיעור",
    noLesson: "ללא שיעור",
    whatsappTab: "ייבוא מוואטסאפ",
    whatsappZipLabel: "בחר קובץ ZIP של ייצוא שיחה",
    whatsappUnzip: "פתח קובץ",
    whatsappUnzipping: "פותח קובץ...",
    whatsappTeacherLabel: "מי בשיחה הוא המורה?",
    whatsappTeacherContinue: "המשך",
    whatsappUploadingVoiceNotes: "מעלה הודעות קוליות...",
    whatsappParsing: "מנתח הודעות עם Gemini...",
    whatsappNoZip: "לא נבחר קובץ",
    whatsappCursorNotice: "מתחיל מהודעות אחרי",
    whatsappImportAll: "ייבא הכל מחדש (כולל הודעות ישנות)",
    linkedRecording: "הקלטה משויכת",
    playLinkedRecording: "נגן",
    colArabicScript: "כתיב ערבי",
    colItemNumber: "מס'",
    committedBadge: "נוסף",
    commitRemaining: "הוסף שורות חדשות",
    pdfTab: "ייבוא PDF",
    batchListTitle: "ייבואים קודמים",
    batchListToggleShow: "הצג ייבואים קודמים",
    batchListToggleHide: "הסתר",
    batchListEmpty: "אין עדיין ייבואים",
    batchReopen: "פתח מחדש",
    batchReparse: "נתח מחדש",
    batchReparsing: "מנתח מחדש...",
    batchSourcePaste: "טקסט",
    batchSourcePhoto: "תמונה",
    batchSourceWhatsapp: "וואטסאפ",
    batchSourcePdf: "PDF",
    pdfFileLabel: "בחר קובץ PDF",
    pdfPageCountLabel: "סה״כ עמודים בקובץ",
    pdfFromPage: "מעמוד",
    pdfToPage: "עד עמוד",
    pdfImport: "ייבא",
    pdfRendering: "מרנדר עמודים...",
    pdfExtracting: "מחלץ פריטים עם Gemini...",
    pdfGapWarningPrefix: "מספרים חסרים ברשימה הממוספרת",
    pdfGapPagesHint: "בדוק עמודים",
    pdfStatusPending: "ממתין",
    pdfStatusProcessing: "מעבד",
    pdfStatusDone: "הושלם",
    pdfStatusFailed: "נכשל",
    pdfRetryPage: "נסה שוב",
    pdfResume: "השלם עמודים שנותרו",
    pdfIncompleteBadge: "יש עמודים שלא הושלמו",
    colApprove: "אישור",
    confidenceFilterLabel: "סינון לפי ביטחון",
    confidenceFilterAll: "הכל",
    confidenceFilterHigh: "גבוהה בלבד",
    confidenceFilterLow: "נמוכה בלבד",
    showReferenceRows: "הצג שורות עמודי עזר",
    hideReferenceRows: "הסתר שורות עמודי עזר",
    referenceRowBadge: "עמוד עזר",
    exportCsv: "ייצוא CSV",
  },

  browse: {
    title: "עיון בכרטיסים",
    searchPlaceholder: "חיפוש לפי תרגום או תעתיק...",
    filterLesson: "שיעור",
    filterType: "סוג",
    filterTypeAll: "הכל",
    noResults: "לא נמצאו כרטיסים",
    playAudio: "נגן",
  },

  notes: {
    title: "פתקים",
    addPlaceholder: "כתוב פתק...",
    tagPlaceholder: "תגית (אופציונלי, למשל: inbox, review)",
    add: "הוסף",
    empty: "אין פתקים פתוחים",
    dismiss: "סגור",
    done: "בוצע",
  },

  recordings: {
    title: "הקלטות",
    upload: "העלאת הקלטה",
    uploading: "מעלה...",
    transcoding: "ממיר אודיו...",
    transcribing: "מתמלל...",
    lessonLabel: "שיעור",
    noRecordings: "אין הקלטות עדיין",
    detailTitle: "פרטי הקלטה",
    transcript: "תמלול",
    noTranscript: "אין תמלול עדיין",
    selectRange: "בחר טווח",
    startLabel: "התחלה",
    endLabel: "סיום",
    nudgeBack: "אחורה",
    nudgeForward: "קדימה",
    attachExisting: "צרף לכרטיס קיים",
    createNew: "צור כרטיס חדש",
    searchCards: "חיפוש כרטיסים",
    attach: "צרף טווח",
    attached: "הטווח צורף בהצלחה",
    clipping: "חותך קטע שמע...",
    mobileClipNotice: "חיתוך קטעים זמין רק במחשב",
    tagFilterLabel: "סינון לפי תגית",
    tagFilterAll: "הכל",
  },

  lessons: {
    title: "שיעורים",
    addNext: "הוסף שיעור הבא",
    dateLabel: "תאריך",
    titleLabel: "כותרת",
    save: "שמור",
    empty: "אין עדיין שיעורים",
  },

  stats: {
    title: "סטטיסטיקה",
    dueToday: "לחזרה היום",
    streak: "רצף ימים",
    totalCards: "סך הכרטיסים",
    matureCards: "כרטיסים בוגרים",
  },

  common: {
    save: "שמור",
    cancel: "ביטול",
    loading: "טוען...",
    error: "משהו השתבש",
    back: "חזרה",
    edit: "עריכה",
    delete: "מחיקה",
  },
};
