export const strings = {
  appName: "יאללה כרטיסים",

  nav: {
    review: "חזרה",
    inbox: "תיבה",
    recordings: "הקלטות",
    stats: "סטטיסטיקה",
    logout: "יציאה",
  },

  login: {
    title: "כניסה",
    passwordLabel: "סיסמה",
    submit: "כניסה",
    error: "סיסמה שגויה",
  },

  review: {
    title: "חזרה יומית",
    remaining: "נותרו",
    newToday: "חדשים היום",
    showAnswer: "הצג תשובה",
    again: "שוב",
    hard: "קשה",
    good: "טוב",
    easy: "קל",
    doneTitle: "סיימת להיום!",
    doneSubtitle: "אין כרטיסים נוספים לחזרה כרגע",
    playAudio: "נגן הקלטה",
    directionHeToAr: "עברית → ערבית",
    directionArToHe: "ערבית → עברית",
  },

  inbox: {
    title: "תיבת קליטה",
    pasteTab: "הדבקת טקסט",
    photoTab: "העלאת תמונה",
    pasteLabel: "הדבק כאן הערות שיעור",
    pasteSubmit: "נתח עם Gemini",
    photoLabel: "בחר תמונה או תמונות של המחברת",
    photoSubmit: "נתח תמונות עם Gemini",
    parsing: "מנתח...",
    tableTitle: "תוצאות לעריכה",
    colTranslit: "תעתיק בניקוד",
    colMeaning: "משמעות בעברית",
    colType: "סוג",
    colConfidence: "רמת ביטחון",
    typeWord: "מילה",
    typePhrase: "ביטוי",
    typeSentence: "משפט",
    confidenceLow: "נמוכה",
    confidenceHigh: "גבוהה",
    deleteRow: "מחק שורה",
    addRow: "הוסף שורה",
    duplicateWarning: "כרטיס דומה כבר קיים",
    commit: "הוסף לחפיסה",
    committing: "שומר...",
    committed: "נוספו הכרטיסים בהצלחה",
    emptyState: "אין עדיין פריטים לעריכה",
    lessonLabel: "שיעור",
    noLesson: "ללא שיעור",
  },

  recordings: {
    title: "הקלטות",
    upload: "העלאת הקלטה",
    uploading: "מעלה...",
    transcoding: "ממיר אודיו...",
    transcribing: "מתמלל...",
    lessonLabel: "שיעור",
    noRecordings: "אין הקלטות עדיין",
    detailTitle: "פרטי הקלטה",
    transcript: "תמלול",
    noTranscript: "אין תמלול עדיין",
    selectRange: "בחר טווח",
    startLabel: "התחלה",
    endLabel: "סיום",
    nudgeBack: "אחורה",
    nudgeForward: "קדימה",
    attachExisting: "צרף לכרטיס קיים",
    createNew: "צור כרטיס חדש",
    searchCards: "חיפוש כרטיסים",
    attach: "צרף טווח",
    attached: "הטווח צורף בהצלחה",
    clipping: "חותך קטע שמע...",
    mobileClipNotice: "חיתוך קטעים זמין רק במחשב",
  },

  stats: {
    title: "סטטיסטיקה",
    dueToday: "לחזרה היום",
    streak: "רצף ימים",
    totalCards: "סך הכרטיסים",
    matureCards: "כרטיסים בוגרים",
  },

  common: {
    save: "שמור",
    cancel: "ביטול",
    loading: "טוען...",
    error: "משהו השתבש",
    back: "חזרה",
    edit: "עריכה",
    delete: "מחיקה",
  },
};
