-- Possessive-suffix drill (note 04cff308), per docs/handoff-inflections-rebuild.md.
--
-- The existing /inflections screen drills verb conjugation in Arabic script with
-- no transliteration, which is why the note says "לא טוב" — the learner is shown
-- content he cannot read, and the "recognition" track actually asks which VERB
-- it is, not which person. That screen is left in place and untouched; this is a
-- separate one, and retiring the old drill is a later decision.
--
-- The column is `feature`, not `person`, so demonstratives (note 5774ff07) reuse
-- the same machinery with values like this_m / that_f — as the spec requires.
--
-- Practice layer: never writes card_srs, review_log or cards.self_score.
--
-- Rollback: drop table possessive_attempts, possessive_forms;

-- One row per (noun, feature). Every form here is chatifai-verified before
-- insert — inflections are never generated by pattern, because a wrong vowel in
-- a minimal-pair drill teaches the wrong thing with no context to rescue it.
create table if not exists possessive_forms (
  id uuid primary key default gen_random_uuid(),
  -- base noun, as the learner already knows it
  base_translit text not null,
  base_arabic text not null,
  base_he text not null,
  -- my | your_m | your_f | his | her | our | your_pl | their,
  -- or this_m / that_f / these ... when the same table carries demonstratives
  feature text not null,
  form_translit text not null,
  form_arabic text not null,
  form_he text not null,
  -- regular | feminine_ta | vowel_base — what happens to the base
  pattern_class text not null default 'regular',
  chatifai_verified boolean not null default false,
  created_at timestamptz not null default now(),
  unique (base_translit, feature)
);

create index possessive_forms_base_idx on possessive_forms (base_translit);

-- Stage-1 trials. `chosen_feature` is what makes this diagnostic rather than
-- just a score: knowing the learner picked "his" when the answer was "her" is
-- the contrast that needs more work.
create table if not exists possessive_attempts (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  stage smallint not null check (stage in (1, 2, 3)),
  base_translit text not null,
  target_feature text not null,
  chosen_feature text,
  contrast_with text,
  correct boolean not null,
  latency_ms integer,
  attempted_at timestamptz not null default now()
);

create index possessive_attempts_contrast_idx
  on possessive_attempts (target_feature, contrast_with, attempted_at desc);

alter table possessive_forms enable row level security;
alter table possessive_attempts enable row level security;
